### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by saran0008** [mith36/XSS-PrO#1]
Traceback (most recent call last):
  File "/home/sfdsfs/XSS-PrO/XSS_PRO.py", line 5, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

**Comment by mith36** [comment]
pip install webdriver_manager

let me know if you are facing any issues after that

**Comment by saran0008** [comment]
Okay bro thanks
