### ISSUE TITLE
Isssue with module line 

### ISSUE THREAD

**Issue by uskolor** [mith36/XSS-PrO#2]
Hi how to fix this .You xss scanner do not work in shell terminal 

python XSS_PRO.py --payloads payload.txt --urls url.txt

Traceback (most recent call last):
  File "/home/ugiel/XSS-PrO/XSS_PRO.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by mith36** [comment]
Hi,
did you tried:
pip install -r requirements.txt

if you done try: **pip install selenium**

**Comment by uskolor** [comment]
Requirement already satisfied: urllib3 in ./.local/lib/python2.7/site-packages (from selenium) (1.26.18)
Installing collected packages: selenium
Successfully installed selenium-3.141.0

But still issue 

from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by mith36** [comment]
Pls refer: https://askubuntu.com/questions/1174496/python-selenium-import-error.

**Comment by uskolor** [comment]
Now start working but you have still a lot of issue .

   
Traceback (most recent call last):
  File "/home/uugiel/XSS-PrO/XSS_PRO.py", line 114, in <module>
    popup_triggered, alert_text = check_popup(url_with_payload, payload)
  File "/home/ugiel/XSS-PrO/XSS_PRO.py", line 46, in check_popup
    driver = get_chrome_driver()


/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x55c92d4454e3 <unknown>
#1 0x55c92d174c76 <unknown>
#2 0x55c92d19b757 <unknown>
#3 0x55c92d19a029 <unknown>
#4 0x55c92d1d8ccc <unknown>

**Comment by mith36** [comment]
I have made a few changes to the code. also, i have added the Chrome web driver.

just clone the new code and run it
